import { StyleSheet } from 'react-native';

export const createDeviceStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    flex: 1,
    textAlign: 'center',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
  },
  connectedSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
  },
  connectedCard: {
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: 16,
    borderWidth: 2,
    borderColor: '#0bda95',
  },
  connectedInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  connectedName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  validityIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    marginBottom: 12,
  },
  validityIndicatorValid: {
    backgroundColor: 'rgba(11, 218, 149, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(11, 218, 149, 0.3)',
  },
  validityIndicatorInvalid: {
    backgroundColor: 'rgba(255, 165, 0, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 165, 0, 0.3)',
  },
  validityText: {
    fontSize: 12,
    color: colors.text,
    fontWeight: '500',
  },
  batchStatusContainer: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  batchStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  batchStatusText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  batchProgress: {
    height: 4,
    backgroundColor: colors.border,
    borderRadius: 2,
    overflow: 'hidden',
  },
  batchProgressFill: {
    height: '100%',
    backgroundColor: '#0bda95',
    borderRadius: 2,
  },
  restartBatchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.card,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginTop: 8,
  },
  restartBatchText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0bda95',
  },
  disconnectButton: {
    backgroundColor: '#fb444a',
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  disconnectButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  scanSection: {
    marginBottom: 24,
  },
  pairedDevicesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 12,
  },
  scanningIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scanButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  refreshButton: {
    flex: 1,
    backgroundColor: '#0bda95',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  refreshButtonActive: {
    backgroundColor: '#fb444a',
  },
  refreshButtonDisabled: {
    backgroundColor: colors.card,
    opacity: 0.5,
  },
  refreshButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  stateIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.card,
    borderRadius: 6,
  },
  stateIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stateIconOn: {
    backgroundColor: 'rgba(11, 218, 149, 0.2)',
  },
  stateIconOff: {
    backgroundColor: 'rgba(251, 68, 74, 0.2)',
  },
  stateText: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
  },
  permissionWarning: {
    fontSize: 12,
    color: '#fb444a',
    marginTop: 8,
    textAlign: 'center',
  },
  listSection: {
    flex: 1,
  },
  listContent: {
    gap: 12,
  },
  deviceCard: {
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deviceCardESP: {
    backgroundColor: '#3a4a3e',
    borderLeftWidth: 3,
    borderLeftColor: '#0bda95',
  },
  espBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(11, 218, 149, 0.2)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 2,
  },
  espBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#0bda95',
  },
  deviceIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(251, 68, 74, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceInfo: {
    flex: 1,
  },
  deviceName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  deviceId: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: 'monospace',
    marginBottom: 2,
  },
  deviceRssi: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 20,
  },
  serialSection: {
    marginTop: 16,
    flex: 1,
  },
  serialHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.card,
    borderRadius: 8,
  },
  serialTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: 'rgba(251, 68, 74, 0.2)',
    borderRadius: 4,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#fb444a',
  },
  liveText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fb444a',
    letterSpacing: 0.5,
  },
  serialControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  clearButton: {
    padding: 8,
    backgroundColor: 'rgba(251, 68, 74, 0.2)',
    borderRadius: 6,
  },
  clearButtonText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  terminalContainer: {
    backgroundColor: '#1a1a1c',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.card,
    overflow: 'hidden',
  },
  terminalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#2a2a2c',
    borderBottomWidth: 1,
    borderBottomColor: colors.card,
  },
  terminalButtons: {
    flexDirection: 'row',
    gap: 6,
  },
  terminalButton: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  terminalTitle: {
    fontSize: 11,
    color: colors.textSecondary,
    fontFamily: 'monospace',
  },
  serialOutput: {
    backgroundColor: '#1a1a1c',
    padding: 12,
    maxHeight: 300,
    minHeight: 150,
  },
  serialText: {
    fontSize: 12,
    color: '#0bda95',
    fontFamily: 'monospace',
    lineHeight: 18,
  },
  serialPlaceholder: {
    fontSize: 12,
    color: colors.textSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 40,
  },
  serialHint: {
    fontSize: 10,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 8,
    paddingHorizontal: 20,
    lineHeight: 14,
  },
  terminalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#2a2a2c',
    borderTopWidth: 1,
    borderTopColor: colors.card,
  },
  terminalFooterText: {
    fontSize: 10,
    color: colors.textSecondary,
    fontFamily: 'monospace',
  },
  terminalBaudRate: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  toggleBluetoothButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(251, 68, 74, 0.2)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#fb444a',
  },
  toggleBluetoothText: {
    fontSize: 12,
    color: '#fb444a',
    fontWeight: '600',
  },
  deviceListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    flexWrap: 'wrap',
    gap: 8,
  },
  toggleFilterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toggleFilterText: {
    fontSize: 13,
    color: colors.text,
    fontWeight: '600',
  },
  deviceListCount: {
    marginBottom: 12,
  },
  deviceCountText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  deviceListActions: {
    flexDirection: 'row',
    gap: 8,
  },
  verifyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#fb444a',
    borderRadius: 6,
  },
  verifyButtonText: {
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: colors.card,
    borderRadius: 6,
  },
  filterButtonText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  filterButtonTextActive: {
    color: '#0bda95',
  },
  deviceCardVerified: {
    borderWidth: 2,
    borderColor: '#0bda95',
    backgroundColor: 'rgba(11, 218, 149, 0.05)',
  },
  deviceNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: 'rgba(11, 218, 149, 0.2)',
    borderRadius: 4,
  },
  verifiedText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#0bda95',
  },
  unverifiedBadge: {
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  verifyingText: {
    fontSize: 11,
    color: '#fb444a',
    fontStyle: 'italic',
    marginTop: 2,
  },
  sensorDataSection: {
    flex: 1,
  },
  sensorDataHeader: {
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  liveIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  sensorDataTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  deviceNameText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  sensorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  sensorCard: {
    width: '48%',
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    gap: 8,
  },
  sensorLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  sensorValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
  },
  npkSection: {
    paddingHorizontal: 16,
    marginTop: 24,
    marginBottom: 16,
  },
  npkGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  npkCard: {
    width: '48%',
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  npkLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 8,
  },
  npkValue: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  trendSection: {
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 24,
  },
  trendHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  trendTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  dataCount: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  chartContainer: {
    marginTop: 12,
    flexDirection: 'row',
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  yAxisLabels: {
    justifyContent: 'space-between',
    paddingVertical: 5,
    marginRight: 8,
    height: 160,
  },
  axisLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  xAxisLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '500',
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    marginTop: 16,
    flexWrap: 'wrap',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '500',
  },
});
