import { StyleSheet } from 'react-native';

export const createSettingsStyles = (colors: any) => StyleSheet.create({
  container: { 
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: { 
    fontSize: 17, 
    fontWeight: '600', 
    flex: 1, 
    textAlign: 'center',
    color: colors.text,
  },
  content: { 
    flex: 1, 
    padding: 16,
  },
  section: {
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    backgroundColor: colors.card,
    borderColor: colors.cardBorder,
  },
  userInfo: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  avatarText: { 
    fontSize: 20, 
    fontWeight: '600',
  },
  userDetails: { 
    flex: 1,
  },
  userName: { 
    fontSize: 15, 
    fontWeight: '600', 
    marginBottom: 3,
    color: colors.text,
  },
  userEmail: { 
    fontSize: 12,
    color: colors.textSecondary,
  },
  settingRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
  },
  settingLeft: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 12, 
    flex: 1,
  },
  settingInfo: { 
    flex: 1,
  },
  settingLabel: { 
    fontSize: 14, 
    fontWeight: '600', 
    marginBottom: 3,
    color: colors.text,
  },
  settingDesc: { 
    fontSize: 11,
    color: colors.textSecondary,
  },
  sectionTitle: { 
    fontSize: 14, 
    fontWeight: '600', 
    marginBottom: 10,
    color: colors.text,
  },
  input: {
    height: 42,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    borderWidth: 1,
    backgroundColor: colors.background,
    color: colors.text,
    borderColor: colors.border,
  },
  languageOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  languageText: { 
    fontSize: 13, 
    fontWeight: '500',
    color: colors.text,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 10,
    marginBottom: 12,
    backgroundColor: colors.success,
  },
  saveText: { 
    fontSize: 14, 
    fontWeight: '600', 
    color: '#ffffff',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 10,
    marginTop: 6,
    backgroundColor: colors.error,
  },
  logoutText: { 
    fontSize: 14, 
    fontWeight: '600', 
    color: '#ffffff',
  },
});
